# Generated by Django 5.2.8 on 2025-12-18 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration_seconds',
        ),
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artist_photos/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
