# Generated by Django 5.2.8 on 2025-12-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_remove_song_duration_seconds_artist_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
