# Generated by Django 5.2.8 on 2025-12-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_song_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
