# Generated by Django 5.2.8 on 2025-12-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_alter_song_duration_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration_seconds',
        ),
    ]
